version: '3'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SCHEMA: certifications
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./config/postgres/initdb:/docker-entrypoint-initdb.d

  keycloak:
    image: keycloak/keycloak:26.4
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/app
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: keycloak
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_URL: http://keycloak.localhost:8082
      KC_FRONTEND_URL: http://keycloak.localhost:8082
      KC_HOSTNAME: keycloak.localhost
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - postgres
    ports:
      - 8082:8080
      - 9000:9000
    extra_hosts:
      - "keycloak.localhost:host-gateway"  

  spring-gateway:
    image: arm64v8/openjdk:21
    container_name: spring-gateway
    volumes:
      - ./build/libs/spring-gateway-1.0.0.jar:/app/spring-gateway.jar
    environment:
      - JAVA_OPTS=-Xmx512m -Djava.awt.headless=true
    ports:
      - "5005:5005"
      - "8080:8080"
    command: sh -c "java $JAVA_OPTS -jar /app/spring-gateway.jar" 
    depends_on:
      - keycloak
      - certification-service 

    extra_hosts:
      - "keycloak.localhost:host-gateway"    

  certification-service:
    image: arm64v8/openjdk:21
    container_name: certification-service
    volumes:
      - ../certifications/build/libs/certifications-0.1.0.jar:/app/certification-service.jar
    environment:
      - JAVA_OPTS="-Dagentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Xmx512m -Djava.awt.headless=true"
    ports:
      - "5006:5005"
      - "8081:8081"
    command: sh -c "java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /app/certification-service.jar" 
    depends_on:
      - postgres
    extra_hosts:
      - "keycloak.localhost:host-gateway"  

volumes:
  pgdata:
    